

export const metadata = {
  title: 'Next ToDo',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <h1>Awesome Todo App </h1>
        {children}</body>
    </html>
  )
}
